[package]
name = "inject-datetime"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
hook-support = { path = "../hook-support" }
serde = { workspace = true }
serde_json = { workspace = true }
