name: Bug report

description: Create a report to help us improve

labels: [bug]

body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide steps and any JSONL inputs used
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior / logs
      description: Attach logs (stderr) and, if applicable, scenario outputs

  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: |
        OS:
        Rust:
        Commit SHA:
