[package]
name = "pre-tool-use-approval"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
hook-support = { path = "../hook-support" }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
