name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - feature/**
      - fix/**
      - perf/**
      - chore/**
      - docs/**

# Required for security-events write permission
permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  # Cross-platform build and test matrix
  build-test:
    strategy:
      matrix:
        # Windows temporarily removed due to Unix-specific code in acplb_notify_forwarder
        # TODO: Re-enable after fixing Windows compatibility (Issue #32)
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy (deny warnings)
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Tests
        run: cargo test --workspace --all-features --locked

  # SDD validation checks
  sdd-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SDD structure lint
        run: bash scripts/ci/run-sdd-structure-lint.sh

      - name: Language policy check (normative artifacts)
        run: bash scripts/ci/check-language-policy.sh

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Protocol scenarios (JSONL replay)
        id: scenarios
        shell: bash
        run: |
          set -euo pipefail
          if compgen -G "dev-docs/review/_artifacts/tests/*.jsonl" > /dev/null; then
            mkdir -p _ci_artifacts/protocol
            for f in dev-docs/review/_artifacts/tests/*.jsonl; do
              out="_ci_artifacts/protocol/$(basename "$f").out.jsonl"
              echo "Running scenario: $f"
              # Run the scenario and capture output
              if RUST_LOG=info cargo run -p codex-cli-acp --bin codex-cli-acp < "$f" > "$out" 2>&1; then
                # Validate output is valid JSONL
                if jq -c . "$out" >/dev/null 2>&1; then
                  echo "✓ Valid JSONL output"
                else
                  echo "⚠ Warning: Output is not valid JSONL"
                fi
              else
                echo "⚠ Warning: Scenario execution failed"
              fi
            done
          else
            echo "No protocol scenarios found, skipping."
          fi

      - name: Upload protocol artifacts
        if: ${{ hashFiles('dev-docs/review/_artifacts/tests/*.jsonl') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: protocol-outputs
          path: _ci_artifacts/protocol

  # ast-grep code scanning with SARIF upload
  # Report-only mode: continues even if violations found
  # TO ENABLE ENFORCEMENT: Remove the continue-on-error line below
  # This should be done after Issue #31 is resolved (see transition.md)
  ast-grep-scan:
    runs-on: ubuntu-latest
    continue-on-error: true  # Report-only mode - won't block PR (remove to enforce)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ast-grep
        uses: taiki-e/install-action@v2
        with:
          tool: ast-grep

      - name: Run ast-grep scan
        id: ast-grep
        run: |
          echo "Running ast-grep scan..."
          # Run ast-grep and capture exit code
          set +e  # Temporarily disable exit on error
          ast-grep scan -c sgconfig.yml --json > ast-grep-results.json
          AST_GREP_EXIT_CODE=$?
          set -e  # Re-enable exit on error

          # Check if scan succeeded (exit 0 or 1 are both ok - 1 means violations found)
          if [ $AST_GREP_EXIT_CODE -gt 1 ]; then
            echo "::error::ast-grep scan failed with exit code $AST_GREP_EXIT_CODE"
            exit $AST_GREP_EXIT_CODE
          fi

          # Show summary in logs
          if [ -s ast-grep-results.json ] && [ "$(jq '. | type' ast-grep-results.json 2>/dev/null)" = '"array"' ]; then
            ISSUE_COUNT=$(jq '. | length' ast-grep-results.json)
            echo "Found $ISSUE_COUNT issues"
            if [ "$ISSUE_COUNT" -gt 0 ]; then
              jq -r '.[] | "\(.severity // "warning"): \(.rule_id) at \(.file):\(.start_line // .line // "?")"' ast-grep-results.json
            fi
          else
            echo "No issues found"
            echo "[]" > ast-grep-results.json
          fi

      - name: Convert to SARIF format
        if: success() || failure()
        run: |
          echo "Converting ast-grep results to SARIF..."
          jq -f scripts/ci/json-to-sarif.jq ast-grep-results.json > results.sarif

          # Validate SARIF output
          if jq -e '.version == "2.1.0"' results.sarif > /dev/null 2>&1; then
            echo "✓ Valid SARIF generated"
          else
            echo "::warning::SARIF validation failed - creating minimal fallback"
            echo "⚠ SARIF validation failed, creating minimal valid SARIF"
            cat > results.sarif <<'EOF'
          {
            "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
            "version": "2.1.0",
            "runs": [{
              "tool": {
                "driver": {
                  "name": "ast-grep",
                  "version": "0.x.x"
                }
              },
              "results": []
            }]
          }
          EOF
          fi

      - name: Upload SARIF to GitHub Code Scanning
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: ast-grep
          wait-for-processing: true

      - name: Upload ast-grep artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: ast-grep-results
          path: |
            ast-grep-results.json
            results.sarif

  # Typos checking for documentation and code
  typos-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install typos
        uses: taiki-e/install-action@v2
        with:
          tool: typos-cli

      - name: Run typos check
        run: |
          echo "Checking for typos..."
          typos || {
            echo "::warning::Typos found. Please review and fix."
            # Don't fail the job for typos
            exit 0
          }